// <auto-generated />
namespace InfinityProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Missintechnicians : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Missintechnicians));
        
        string IMigrationMetadata.Id
        {
            get { return "201703221221411_Missintechnicians"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
